# Refer to the README.md file in within this service directory to configure all ssm parameters required for this service.
service: app-api

frameworkVersion: "2"

package:
  individually: true

plugins:
  - serverless-bundle
  - serverless-dotenv-plugin
  - serverless-plugin-warmup
  - serverless-associate-waf
  - serverless-offline
  - serverless-stack-termination-protection
  - serverless-idempotency-helper
  - serverless-iam-helper
  - serverless-s3-bucket-helper

custom:
  stage: ${opt:stage, self:provider.stage}
  region: ${opt:region, self:provider.region}
  serverlessTerminationProtection:
    stages:
      - master
      - val
      - production
  coreSetTableName: ${env:DYNAMO_TABLE_NAME, cf:database-${self:custom.stage}.CoreSetTableName}
  coreSetTableArn: ${env:DYNAMO_TABLE_ARN, cf:database-${self:custom.stage}.CoreSetTableArn}
  measureTableName: ${env:DYNAMO_TABLE_NAME, cf:database-${self:custom.stage}.MeasureTableName}
  measureTableArn: ${env:DYNAMO_TABLE_ARN, cf:database-${self:custom.stage}.MeasureTableArn}
  webAclName: ${self:service}-${self:custom.stage}-webacl
  associateWaf:
    name: ${self:custom.webAclName}
    version: V2
  warmup:
    default:
      enabled: true
      prewarm: true
      events:
        - schedule: rate(${ssm:/configuration/${self:custom.stage}/warmup/schedule~true, ssm:/configuration/default/warmup/schedule~true, "4 minutes"})
      concurrency: ${ssm:/configuration/${self:custom.stage}/warmup/concurrency~true, ssm:/configuration/default/warmup/concurrency~true, 5}

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  logs:
    restApi: true
  iam:
    role:
      path: ${ssm:/configuration/${self:custom.stage}/iam/path~true, ssm:/configuration/default/iam/path~true, "/"}
      permissionsBoundary: ${ssm:/configuration/${self:custom.stage}/iam/permissionsBoundaryPolicy~true, ssm:/configuration/default/iam/permissionsBoundaryPolicy~true, ""}
      statements:
        - Effect: "Allow"
          Action:
            - dynamodb:DescribeTable
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - ${self:custom.CoreSetTableArn}
            - ${self:custom.MeasureTableArn}
  environment:
    coreSetTableName: ${self:custom.coreSetTableName}
    measureTableName: ${self:custom.measureTableName}

functions:
  listMeasures:
    handler: handlers/measures/get.listMeasures
    events:
      - http:
          path: coreset/{state}/{year}/{coreSetId}/measures
          method: get
          cors: true
          authorizer: aws_iam
  listMeasuresMetadata:
    handler: handlers/measures/get.listMeasuresMetadata
    events:
      - http:
          path: coreset/{state}/{year}/{coreSetId}/measures/metadata
          method: get
          cors: true
          authorizer: aws_iam
  getMeasure:
    handler: handlers/measures/get.getMeasure
    events:
      - http:
          path: coreset/{state}/{year}/{coreSetId}/measures/{measureId}
          method: get
          cors: true
          authorizer: aws_iam
  createMeasure:
    handler: handlers/measures/alter.createMeasure
    events:
      - http:
          path: coreset/{state}/{year}/{coreSetId}/measures/{measureId}
          method: post
          cors: true
          authorizer: aws_iam
  editMeasure:
    handler: handlers/measures/alter.editMeasure
    events:
      - http:
          path: coreset/{state}/{year}/{coreSetId}/measures/{measureId}
          method: put
          cors: true
          authorizer: aws_iam
  deleteMeasure:
    handler: handlers/measures/delete.deleteMeasure
    events:
      - http:
          path: coreset/{state}/{year}/{coreSetId}/measures/{measureId}
          method: delete
          cors: true
          authorizer: aws_iam
  getAllCoreSets:
    handler: handlers/coreSets/get.coreSetList
    events:
      - http:
          path: coreset/{state}/{year}
          method: get
          cors: true
          authorizer: aws_iam
  getCoreSet:
    handler: handlers/coreSets/get.getCoreSet
    events:
      - http:
          path: coreset/{state}/{year}/{coreSetId}
          method: get
          cors: true
          authorizer: aws_iam
  createCoreSet:
    handler: handlers/coreSets/create.createCoreSet
    events:
      - http:
          path: coreset/{state}/{year}/{coreSetId}
          method: post
          cors: true
          authorizer: aws_iam
  editCoreSet:
    handler: handlers/coreSets/update.editCoreSet
    events:
      - http:
          path: coreset/{state}/{year}/{coreSetId}
          method: put
          cors: true
          authorizer: aws_iam
  deleteCoreSet:
    handler: handlers/coreSets/delete.deleteCoreSet
    events:
      - http:
          path: coreset/{state}/{year}/{coreSetId}
          method: delete
          cors: true
          authorizer: aws_iam

resources:
  Resources:
    GatewayResponseDefault4XX:
      Type: "AWS::ApiGateway::GatewayResponse"
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId: !Ref ApiGatewayRestApi
    GatewayResponseDefault5XX:
      Type: "AWS::ApiGateway::GatewayResponse"
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_5XX
        RestApiId: !Ref ApiGatewayRestApi
    ApiGwWebAcl:
      Type: AWS::WAFv2::WebACL
      Properties:
        Name: ${self:custom.webAclName}
        DefaultAction:
          Block: {}
        Rules:
          - Action:
              Allow: {}
            Name: ${self:custom.webAclName}-allow-usa-plus-territories
            Priority: 0
            Statement:
              GeoMatchStatement:
                CountryCodes:
                  - GU # Guam
                  - PR # Puerto Rico
                  - US # USA
                  - UM # US Minor Outlying Islands
                  - VI # US Virgin Islands
                  - MP # Northern Mariana Islands
            VisibilityConfig:
              SampledRequestsEnabled: true
              CloudWatchMetricsEnabled: true
              MetricName: WafWebAcl
        Scope: REGIONAL
        VisibilityConfig:
          CloudWatchMetricsEnabled: true
          SampledRequestsEnabled: true
          MetricName: ${self:custom.stage}-webacl
  Outputs:
    ApiGatewayRestApiName:
      Value: !Ref ApiGatewayRestApi
    ApiGatewayRestApiUrl:
      Value: !Sub https://${ApiGatewayRestApi}.execute-api.${self:provider.region}.amazonaws.com/${self:custom.stage}
    Region:
      Value: !Sub ${AWS::Region}
