version: "2"         # required to adjust maintainability checks
checks:
  argument-count:
    enabled: false
  complex-logic:
    enabled: false
  method-lines:
    config:
      threshold: 300
  file-lines:
    config:
      threshold: 1000  
  method-complexity:
    config:
      threshold: 20
  return-statements:
    enabled: false
  similar-code:
    enabled: false
  identical-code:
    enabled: false
exclude_patterns:
  - "**/node_modules/"
  - ".github/"
  - ".images/"
  - "cypress/"
  - "plugins/"
  - "src/"
  - "services/.sechub/"
  - "services/database/"
  - "services/stream-functions/"
  - "services/ui/"
  - "services/ui-auth/"
  - "services/uploads/"
  - "tests/"
  - "**/*.test.tsx"
