exclude_patterns:
  - "**/node_modules/"
  - "**/.github/"
  - "**/.images/"
  - "**/cypress/"
  - "**/plugins/"
  - "**/src/"
  - "**/services/.sechub/"
  - "**/services/database"
  - "**/services/stream-functions"
  - "**/services/ui"
  - "**/services/ui-auth"
  - "**/services/uploads"
  - "**/tests/"
  