version: "2"
checks:
  method-lines:
    config:
      threshold: 100
exclude_patterns:
  - "tests/"
  - "__tests__/"
  - "**/*test*"
  - "**/components/index.tsx"
  - "**/pages/index.tsx"
  - "**/libs/index.tsx"
