services:
  # wave 1: no dependencies
  database:
    path: services/database
  ui:
    path: services/ui

  # wave 2: depends on database
  uploads:
    path: services/uploads
  app-api:
    path: services/app-api

  # wave 3: depends on many
  ui-auth:
    path: services/ui-auth

  # wave 4: depends on many
  ui-src:
    path: services/ui-src
