service: database

frameworkVersion: "3"

plugins:
  - serverless-dynamodb
  - serverless-stack-termination-protection
  - serverless-s3-bucket-helper

custom:
  project: "qmr"
  stage: ${opt:stage, self:provider.stage}
  region: ${opt:region, self:provider.region}
  serverlessTerminationProtection:
    stages:
      - master
      - val
      - prod
  coreSetTableName: ${self:custom.stage}-coreSets
  measureTableName: ${self:custom.stage}-measures
  bannerTableName: ${self:custom.stage}-banners
  rateTableName: ${self:custom.stage}-rates
  measureTable: ${self:custom.stage}-measure
  dynamodb:
    stages:
      - local
    start:
      port: 8000
      inMemory: true
      migrate: true

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stackTags:
    PROJECT: ${self:custom.project}
    SERVICE: ${self:service}

resources:
  Resources:
    CoreSetTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.coreSetTableName}
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
        AttributeDefinitions:
          - AttributeName: compoundKey
            AttributeType: S
          - AttributeName: coreSet
            AttributeType: S
        KeySchema:
          - AttributeName: compoundKey
            KeyType: HASH
          - AttributeName: coreSet
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST # Set the capacity to auto-scale
    RateTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.rateTableName}
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
        AttributeDefinitions:
          - AttributeName: compoundKey
            AttributeType: S
          - AttributeName: measure
            AttributeType: S
        KeySchema:
          - AttributeName: compoundKey
            KeyType: HASH
          - AttributeName: measure
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST # Set the capacity to auto-scale
    MeasureTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.measureTableName}
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
        AttributeDefinitions:
          - AttributeName: compoundKey
            AttributeType: S
          - AttributeName: coreSet
            AttributeType: S
        KeySchema:
          - AttributeName: compoundKey
            KeyType: HASH
          - AttributeName: coreSet
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST # Set the capacity to auto-scale
    BannerTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.bannerTableName}
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
        AttributeDefinitions:
          - AttributeName: key
            AttributeType: S
        KeySchema:
          - AttributeName: key
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST # Set the capacity to auto-scale
    QualityMeasureTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.measureTable}
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
        AttributeDefinitions:
          - AttributeName: compoundKey
            AttributeType: S
          - AttributeName: measure
            AttributeType: S
        KeySchema:
          - AttributeName: compoundKey
            KeyType: HASH
          - AttributeName: measure
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST # Set the capacity to auto-scale
  Outputs:
    CoreSetTableName:
      Value: !Ref CoreSetTable
    CoreSetTableArn:
      Value: !GetAtt CoreSetTable.Arn
    CoreSetTableStreamArn:
      Value: !GetAtt CoreSetTable.StreamArn
    MeasureTableName:
      Value: !Ref MeasureTable
    MeasureTable:
      Value: !Ref QualityMeasureTable
    MeasureTableArn:
      Value: !GetAtt MeasureTable.Arn
    MeasureTableStreamArn:
      Value: !GetAtt MeasureTable.StreamArn
    RateTableName:
      Value: !Ref RateTable
    RateTableArn:
      Value: !GetAtt RateTable.Arn
    RateTableStreamArn:
      Value: !GetAtt RateTable.StreamArn
    BannerTableName:
      Value: !Ref BannerTable
    BannerTableArn:
      Value: !GetAtt BannerTable.Arn
    Region:
      Value: !Sub ${AWS::Region}
