service: database

frameworkVersion: "3"

plugins:
  - serverless-dynamodb-local
  - serverless-stack-termination-protection
  - serverless-s3-bucket-helper

custom:
  stage: ${opt:stage, self:provider.stage, "local"}
  region: ${opt:region, self:provider.region}
  serverlessTerminationProtection:
    stages:
      - master
      - val
      - prod
  coreSetTableName: ${self:custom.stage}-coreSets
  measureTableName: ${self:custom.stage}-measures
  dynamodb:
    stages:
      - local
    start:
      port: 8000
      inMemory: true
      migrate: true

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1

resources:
  Resources:
    CoreSetTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.coreSetTableName}
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
        AttributeDefinitions:
          - AttributeName: compoundKey
            AttributeType: S
          - AttributeName: coreSet
            AttributeType: S
        KeySchema:
          - AttributeName: compoundKey
            KeyType: HASH
          - AttributeName: coreSet
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST # Set the capacity to auto-scale

    MeasureTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.measureTableName}
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
        AttributeDefinitions:
          - AttributeName: compoundKey
            AttributeType: S
          - AttributeName: coreSet
            AttributeType: S
        KeySchema:
          - AttributeName: compoundKey
            KeyType: HASH
          - AttributeName: coreSet
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST # Set the capacity to auto-scale
  Outputs:
    CoreSetTableName:
      Value: !Ref CoreSetTable
    CoreSetTableArn:
      Value: !GetAtt CoreSetTable.Arn
    CoreSetTableStreamArn:
      Value: !GetAtt CoreSetTable.StreamArn
    MeasureTableName:
      Value: !Ref MeasureTable
    MeasureTableArn:
      Value: !GetAtt MeasureTable.Arn
    MeasureTableStreamArn:
      Value: !GetAtt MeasureTable.StreamArn
    Region:
      Value: !Sub ${AWS::Region}
