name: Pull request pre-commit check

on: [pull_request]

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Configure pre-commit to skip branch name validation
        run: |
          echo "SKIP=branch-name-validation" >> $GITHUB_ENV
      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files
