name: Pull Request

on:
  pull_request:
    branches:
      - "master"

permissions:
  id-token: write
  contents: read
  actions: read
  pull-requests: write

jobs:
  assignAuthor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Assign PR to Creator
        run: |
          if [ "$PR_AUTHOR_TYPE" != "Bot" ]
            then
              gh pr edit $PRNUM --add-assignee $PR_AUTHOR
            fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRNUM: ${{ github.event.pull_request.number }}
          PR_AUTHOR: ${{ github.event.pull_request.user.login }}
          PR_AUTHOR_TYPE: ${{ github.event.pull_request.user.type }}
  unit-tests:
    name: Unit Tests
    uses: ./.github/workflows/unittest-workflow.yml
    secrets:
      CODE_CLIMATE_ID: ${{ secrets.CODE_CLIMATE_ID }}

  #Notify the integrations channel only when a Snyk auto merge fails pr checks
  notify_on_pr_failure:
    runs-on: ubuntu-latest
    needs: 
      - unit-tests
    #only check branch names that begin with snyk-
    if: ${{ failure() && startsWith(github.head_ref, 'snyk-') }}
    steps:
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_TITLE: ":boom: A Synk auto merge has failed pull request checks in ${{ github.repository }}."
          MSG_MINIMAL: true
          SLACK_WEBHOOK: ${{ secrets.INTEGRATIONS_SLACK_WEBHOOK }}
